# Generated by Django 2.1.5 on 2019-03-12 03:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('retail', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0, message='The retail needs to be greater than 0')])),
                ('release', models.IntegerField()),
                ('description', models.TextField(max_length=280)),
            ],
        ),
    ]
