# Generated by Django 2.1.5 on 2019-03-13 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_cleaning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleaning',
            old_name='part',
            new_name='state',
        ),
    ]
