# Generated by Django 2.1.5 on 2019-03-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190313_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='marketplaces',
            field=models.ManyToManyField(to='main_app.Marketplace'),
        ),
    ]
